#  Pruebas

In [1]:
include("../Codigo/tesis/main.jl")

WebIO._IJuliaInit()

circulo (generic function with 1 method)

push!(LOAD_PATH,"/home/rogve98/Documentos/Tesis/Tesis/Código/Codigo/tesis")

import main

In [41]:
#PARÁMETROS
N = 100
x0 = ones(N)
t0 = 0
tf = 50
h = 0.01
σ = 0.2
p = 0.2
r = 2*ones(N)
K = 5*ones(N)
params = Parametros(N::Int,σ::Float64,p::Float64,x0::Vector,t0::Int,tf::Int,h::Float64,r::Vector,K::Vector)

Parametros(100, 0.2, 0.2, [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0  …  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], 0, 50, 0.01, [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0  …  2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0], [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0  …  5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0])

In [3]:
s = poblacionesLK(params)

Soluciones(0.0:0.01:50.0, [1.0 1.0 … 1.0 1.0; 1.0181108035947002 1.0148339703809797 … 1.0157560284614955 1.01771688352955; … ; 5.110715429081713 3.8592133474829287e-10 … 5.876512570126031 11.2458496964855; 5.110715178050988 3.8421908633205356e-10 … 5.876513063300678 11.245849398195551], [1.0 1.0 … 1.0 1.0; 1.0179781875168867 1.0147698433854422 … 1.0156643648559909 1.0175829758393173; … ; 5.110714587974966 3.6851946407181963e-10 … 5.876514093528178 11.245848721424757; 5.110714337099205 3.668903770264099e-10 … 5.876514584951597 11.24584842383525], [1.0 0.0 … 0.0 0.0; 0.0 1.0 … 0.0 -0.002935103541871386; … ; 0.0 0.0 … 1.0 0.0; 0.0 0.3506331889746672 … 0.0 1.0], SimpleGraph{Int64}(989, [[7, 9, 23, 26, 32, 33, 48, 51, 54, 56, 68, 70, 76, 77, 79, 81, 82, 83, 84], [9, 16, 28, 38, 47, 53, 60, 61, 66, 70, 72, 78, 79, 96, 97, 100], [4, 15, 16, 18, 25, 28, 30, 32, 37, 42  …  46, 48, 49, 54, 55, 69, 72, 79, 90, 97], [3, 9, 12, 20, 32, 35, 36, 38, 43, 45, 46, 56, 64, 65, 67, 69, 70, 82, 88], [6, 15

In [4]:
esEstable(s.rk4)

true

In [13]:
X = 10*rand(100)

100-element Vector{Float64}:
 1.1441563543035072
 2.0100791676036858
 3.9008947113542614
 3.952512577631364
 4.476750524253256
 3.4268466830064135
 2.171221697013186
 9.684562869893279
 1.646450964878624
 5.852902151230652
 3.0001909324195464
 9.076438366276877
 2.1692120443043073
 ⋮
 8.506874328309491
 7.606082146263388
 6.090973708017801
 6.620498805870751
 8.634734353575311
 7.2132250608034525
 1.8948409329029037
 4.098487533360529
 2.75990349279453
 6.743681343136096
 6.021929026051026
 7.466310035707978

In [15]:
P = [params.r,params.K,params.N,s.A]
puntoC = nrMulti(Jacobiano,X,P,2000)

100-element Vector{Float64}:
  0.0
  0.0
  1.4052107826273943
  0.0
  0.0
  0.0
  8.82687781216156
 13.038236166338653
  0.0
 -1.8434266332727238
  3.3461790315382185
  0.0
  0.0
  ⋮
 -1.844697174881931
  0.0
  0.0
  1.5764872655627737
  4.011098820283857
  6.262742416211444
  4.793555396844493
  0.0
  0.0
  2.7216996819098704
  9.551409375236451
  8.132040625634096

In [16]:
J = Jacobiano(puntoC,P)

100×100 Matrix{Float64}:
  2.71694   -0.0      -0.0       …  -0.0       -0.0        -0.0
 -0.0        1.72958  -0.0          -0.0       -0.0         0.0
 -0.0       -0.0      -0.562084     -0.0       -0.0        -0.0
 -0.0       -0.0      -0.0          -0.0       -0.0        -0.0
 -0.0       -0.0      -0.0          -0.0        0.0        -0.0
 -0.0       -0.0      -0.0       …  -0.0       -0.0        -0.0
  0.895536  -0.0      -0.0          -0.0       -0.0        -0.786976
 -0.0       -0.0      -0.0          -0.0       -0.0        -0.0
  0.0        0.0      -0.0          -0.0        0.0        -0.0
  0.0        0.0       0.0           0.0        0.0         0.0
 -0.0       -0.0      -0.0       …  -0.0       -0.536074   -0.0
 -0.0       -0.0      -0.0          -0.0        0.0        -0.0
 -0.0       -0.0      -0.0          -0.0       -0.0        -0.0
  ⋮                              ⋱                         
  0.0        0.0       0.0           0.0        0.0         0.0
 -0.0       -0

In [17]:
ev1 = eigvals(J)

100-element Vector{ComplexF64}:
 -6.241151900812652 - 0.7811937321987099im
 -6.241151900812652 + 0.7811937321987099im
 -4.901511083552992 + 0.0im
 -4.056279432164792 + 0.0im
 -3.767081003856218 + 0.0im
 -3.750642112636731 - 0.45366730126750215im
 -3.750642112636731 + 0.45366730126750215im
 -3.243769802402659 - 0.8325799346180282im
 -3.243769802402659 + 0.8325799346180282im
 -3.228833114050198 + 0.0im
  -3.11475312588692 - 0.3208806998513378im
  -3.11475312588692 + 0.3208806998513378im
 -3.088621001305673 + 0.0im
                    ⋮
 2.5671253474848266 + 0.0im
 2.5909892748466774 + 0.0im
 2.7169417307527706 + 0.0im
  2.830456839704362 + 0.0im
 2.9511483682301125 + 0.0im
  3.280436944597842 + 0.0im
  3.397775817800616 + 0.0im
 3.4487988445342164 + 0.0im
  4.003319608514724 + 0.0im
  4.116204168981075 + 0.0im
  4.655528370482198 + 0.0im
  5.006639703914745 + 0.0im

In [18]:
r = sqrt(params.N*params.p)
scatter(real(ev1),imag(ev1))
plot!(circulo(0,0,1),seriestype=:shape,
    lw=0.5,
    c = :blue,
    linecolor = :black,
    legend = false,
    fillalpha = 0.2,
    aspect_ratio = 1
)

In [54]:
M = interacciones(params.N,params.p,params.σ,1)

([-0.22360679774997896 0.0 … 0.0 0.0; 0.0 -0.22360679774997896 … 0.0 0.0; … ; 0.0 0.0 … -0.22360679774997896 -0.01860584295099271; 0.0 0.0 … 0.0326127639295492 -0.22360679774997896], SimpleGraph{Int64}(978, [[3, 7, 10, 12, 19, 21, 22, 27, 29, 40  …  55, 62, 65, 66, 72, 74, 82, 93, 95, 98], [4, 6, 19, 20, 23, 33, 38, 40, 44, 47  …  65, 71, 79, 81, 82, 85, 90, 92, 94, 98], [1, 7, 15, 20, 35, 46, 47, 48, 58, 71, 74, 76, 95], [2, 8, 43, 44, 45, 50, 52, 53, 60, 61  …  69, 72, 80, 81, 82, 90, 92, 96, 99, 100], [13, 26, 30, 31, 34, 37, 38, 39, 42, 44  …  62, 63, 69, 70, 76, 82, 85, 91, 92, 98], [2, 9, 14, 32, 33, 34, 39, 40, 47, 67, 86, 91, 99], [1, 3, 11, 15, 23, 31, 39, 51, 53, 58, 59, 60, 64, 66, 75, 78, 81, 88], [4, 12, 14, 29, 46, 48, 50, 61, 63, 66, 68, 76, 78, 88, 98, 99], [6, 13, 29, 30, 31, 42, 51, 53, 56, 76, 88, 93, 98], [1, 12, 27, 28, 34, 39, 51, 54, 57, 63, 67, 77, 88]  …  [5, 6, 19, 21, 31, 34, 40, 44, 50, 53, 66, 68, 70, 81, 89, 94], [2, 4, 5, 12, 14, 16, 27, 36, 42, 43  …  48

In [55]:
ev2 = eigvals(M[1])

100-element Vector{ComplexF64}:
  -0.42207690886909816 + 0.0im
  -0.40409451652619394 + 0.0im
   -0.4030450239487616 - 0.09312829945940197im
   -0.4030450239487616 + 0.09312829945940197im
   -0.3968747132345052 - 0.054761403150655336im
   -0.3968747132345052 + 0.054761403150655336im
   -0.3634807422697457 - 0.024609172038912833im
   -0.3634807422697457 + 0.024609172038912833im
   -0.3606936428913339 - 0.1312407488116361im
   -0.3606936428913339 + 0.1312407488116361im
  -0.35128170505754863 + 0.0im
  -0.34931913901629263 - 0.08928269319808303im
  -0.34931913901629263 + 0.08928269319808303im
                       ⋮
  -0.09884657353129056 + 0.01462361843845573im
  -0.09644347063538292 - 0.057383612222179886im
  -0.09644347063538292 + 0.057383612222179886im
  -0.09254025980516765 - 0.0837951840217632im
  -0.09254025980516765 + 0.0837951840217632im
  -0.08902105462319494 + 0.0im
  -0.05692722764006392 + 0.0im
 -0.045950025945047615 - 0.01706008926945972im
 -0.045950025945047615 + 0.0170600

In [56]:
r = sqrt(params.N*params.p)
scatter(real(ev2),imag(ev2))
plot!(circulo(-0.2,0,0.2),seriestype=:shape,
    lw=0.5,
    c = :blue,
    linecolor = :black,
    legend = false,
    fillalpha = 0.2,
    aspect_ratio = 1
)