# Sistema de $N$ especies en competencia.

24/agosto/2022

Resumen: la idea es generar el primer paso de mi tesis comprobando la ley circular dada por Robert May y extendida por Stefano. El objetivo es generar sistemas de 5 y 10 especies en competencia con valores aleatorios en la matriz de interacciones, y ver si cumple la ley circular.

Para ello, de entrada se necesitará que los valores propios de la matriz tengan parte real negativa.

In [1]:
using LinearAlgebra
using Plots

plotlyjs()

WebIO._IJuliaInit()

Plots.PlotlyJSBackend()

In [2]:
"""RK4

Runge-Kutta 4. Es un integrador para resolver sistemas de ecuaciones diferenciales aunque
probablemente también pueda resolver ecuaciones diferenciales normales.

Parámetros:

f := función de variables Real
x0 := condiciones iniciales del sistema dinámico
t0 := tiempo inicial
tf := tiempo final
h := paso de integración
"""

function RK4(f,x0,t0,tf,h)
    #=al igual que en la función de eulerND, definimos una matriz de dimensión 
    (número de iteraciones × dimensión del sistema dinámico) como conjunto solución=#
    t = range(t0, stop = tf, step = h)
    n = length(t)
    dim = length(x0)
    #lo hacemos en un arreglo de ceros
    xs = zeros(n,dim)
    #imponemos la condición inicial en el primer renglón
    xs[1,:] = x0
    #generamos un ciclo for con las iteraciones de runge-kutta de cuarto orden
    for i in  2:n
        k1 = f(xs[i-1,:])
        k2 = f(xs[i-1,:]+(h/2)*k1)
        k3 = f(xs[i-1,:]+(h/2)*k2)
        k4 = f(xs[i-1,:]+h*k3)
        
        xs[i,:] = xs[i-1,:] + (h/6)*(k1+2*k2+2*k3+k4)
    end
    #=regresamos el resultado en una tupla, con los tiempos en la primera entrada y 
    el conjunto solución en la segunda entrada=#
    return (t , xs)
end


RK4 (generic function with 1 method)

Utilizar la función `randn()` para generar númeror aleatorios bajo la distribución normal.

In [3]:
using Random
rng = MersenneTwister(1234)
randn!(rng, zeros(5,5))

5×5 Matrix{Float64}:
  0.867347   2.21188   -0.560501    0.110096    1.56417
 -0.901744   0.532813  -0.0192918  -0.251176   -1.39674
 -0.494479  -0.271735   0.128064    0.369714    1.1055
 -0.902914   0.502334   1.85278     0.0721164  -1.10673
  0.864401  -0.516984  -0.827763   -1.50343    -3.21136

In [4]:
function hola(X)
    A = [rand() rand();rand() rand()]
    return A*X
end

hola (generic function with 1 method)

In [5]:
hola([1,1])

2-element Vector{Float64}:
 1.7570328084752393
 0.9186354043512641

In [6]:
randn(5,5) - Matrix(1I,5,5)
#Matrix(1I,5,5)

5×5 Matrix{Float64}:
 -2.09895   -0.77457   -0.948326  -0.423121   0.295083
  1.61905   -0.920922  -0.279837  -1.29848    0.072676
  0.132874  -1.01613   -3.42236   -0.583507   0.227965
  0.360421  -1.0011     1.79581   -1.46896    0.0122499
 -0.280743   1.1171     0.555955   1.04169   -0.383921

### 30 enero 2023

In [7]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

In [8]:
#Red aleatoria
M = randomMatrix(5,0.25)
display(M)
gplot(g,nodelabel = 1:5)

LoadError: UndefVarError: randomMatrix not defined

In [9]:
x0 = [rand(), rand(), rand(), rand(), rand()]
#x0 = [rand(),1]
t0 = 0
tf = 20
dt = 0.1

t, sol = cincoEspecies(x0,t0,tf,dt,M)

LoadError: UndefVarError: cincoEspecies not defined

In [10]:
plot(t,sol[:,1],label ="Especie 1",w=2)

plot!(t,sol[:,2],label ="Especie 2",w=2)
plot!(t,sol[:,3],label ="Especie 3",w=2)
plot!(t,sol[:,4],label ="Especie 4",w=2)
plot!(t,sol[:,5],label ="Especie 5",w=2)

LoadError: UndefVarError: sol not defined

In [11]:
plot(sol[:,1],sol[:,3],w=2,
    #xlabel = "Tiempo",
    xlabel = "Conejos",
    ylabel = "Ovejas",
    label = "",
)

LoadError: UndefVarError: sol not defined

Encontrar puntos fijos y averiguar si se trata de atractores o repulsores. Aquí mi primera interpretación es que las ovejas ganan y los conejos se extinguen.

## 7 de febrero 2022

Continuamos con el trabajo revisando fallas de los modelos. Vamos a hacer pruebas para 2 especies y de ahí extenderlo a los otros sistemas.

$$
\frac{dx_i}{dt}=r_ix_i\left(1-\frac{\sum_{j=1}^N \alpha_{ij}x_j}{K_i}\right)
$$





\begin{cases}
\dot{x}_1&=r_1x_1(1-\frac{a_{11}x_1}{k_1}-\frac{a_{12}x_1x_2}{k_1})\\
\dot{x}_2&=r_2x_2(1-\frac{a_{21}x_2}{k_2}-\frac{a_{22}x_1x_2}{k_2})
\end{cases}

In [12]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

In [13]:
A,g = randomMatrix(2,0.6)
display(A)
gplot(g,nodelabel = 1:2)

LoadError: UndefVarError: randomMatrix not defined

In [14]:
x0 = sample(1:0.1:4,2)
t0 = 0
tf = 20
dt = 0.1

t, sol = pruebas(x0,t0,tf,dt,A)

LoadError: UndefVarError: sample not defined

In [15]:
p1 = plot(t,sol[:,1],label ="Especie 1",w=2)
plot!(t,sol[:,2],label ="Especie 2",w=2)

p2 = plot(sol[:,1],sol[:,2],w=2,
    #xlabel = "Tiempo",
    xlabel = "Conejos",
    ylabel = "Ovejas",
    label = "",
    xlim = [0,4],
    ylim = [0,4]
)
scatter!((sol[1,1],sol[1,2]),label="T=t0")
plot(p1,p2,size=(900,400))

LoadError: UndefVarError: sol not defined

In [16]:
r = [2,3]
K = [2,3]
function prueba(X)
    sis = zeros(2)
    xs = zeros(2)
    for i in 1:2
        for j in 1:2
            xs[i] += A[i,j]*X[j]
        end
        sis[i] = r[i]*X[i]*(1-xs[i]/K[i])
    end
    return xs
end

prueba (generic function with 1 method)

# 10 de febrero 2023

Ya corregí el sistema, hice la respectiva prueba con un sistema de dos por dos, y encontré varios obstáculos; sobre todo aspectos del sistema que no estaban del todo correctos. Fueron corregidos con base en la función de la celda anterior y a continuación serán implementados en los sistemas de 5 y 10 especies. La idea es que estos sistemas respeten su capacidad de carga.

In [17]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

\begin{cases}
\dot{x}_1&=0.5x_1(1-\frac{0.1x_1}{2}-\frac{0.7x_1x_2}{2})\\
\dot{x}_2&=0.7x_2(1-\frac{2.1x_2}{3}-\frac{1.2x_1x_2}{1.2}
\end{cases}

In [18]:
#A = [r1/k1 r1α/k1;r2β/k2 r2/k2]
#A = [0.5 0.7;2.1 1.2]
r = [0.3,0.7]
K = [2,3]
x0 = [1.7,0.4]
t0 = 0
tf = 50
dt = 0.01

t, sol = pruebas(x0,t0,tf,dt,r,K)

LoadError: UndefVarError: pruebas not defined

In [19]:
p1 = plot(t,sol[:,1],label ="",w=2)
plot!(t,sol[:,2],label ="",w=2)

p2 = plot(sol[:,1],sol[:,2],w=2,
    #xlabel = "Tiempo",
    xlabel = "Conejos",
    ylabel = "Ovejas",
    label = "",
    xlim = [0,4],
    ylim = [0,4]
)
scatter!((sol[1,1],sol[1,2]),label="")
plot(p1,p2,size=(900,400))

LoadError: UndefVarError: sol not defined

In [20]:
function unaEspecie(x0,t0,tf,dt)
    r = 0.2
    K = 3.
    function sistema(X)
        return [r*X[1]*(1-X[1]/K)]
    end
    
    return RK4(sistema,x0,t0,tf,dt)
end

unaEspecie (generic function with 1 method)

In [21]:
x0 = [1]
t0 = 0
tf = 20
dt = 0.1

t, sol = unaEspecie(x0,t0,tf,dt)

(0.0:0.1:20.0, [1.0; 1.0133774790146686; … ; 2.8919250623753268; 2.8939894677146145;;])

In [22]:
plot(t,sol)

In [23]:
M,g = randomMatrix(5,0.1)
display(M)
gplot(g,nodelabel = 1:5)

LoadError: UndefVarError: randomMatrix not defined

In [24]:
x0 = sample(1:0.1:5,5)
t0 = 0
tf = 20
dt = 0.1

t, sol5 = cincoEspecies(x0,t0,tf,dt,M)

LoadError: UndefVarError: sample not defined

In [25]:
plot(t,sol5[:,1],label ="Especie 1",w=2,
    title = "5 Especies en competencia",
    xlabel = "Tiempo",
    ylabel = "N_(t)"
)
plot!(t,sol5[:,2],label ="Especie 2",w=2)
plot!(t,sol5[:,3],label ="Especie 3",w=2)
plot!(t,sol5[:,4],label ="Especie 4",w=2)
plot!(t,sol5[:,5],label ="Especie 5",w=2)

LoadError: UndefVarError: sol5 not defined

## 15 de febrero

Vamos a intentar corregir el modelo modificando la entrada $a_{ii}$ de la matriz A.

In [26]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

In [27]:
#A = [r1/k1 r1α/k1;r2β/k2 r2/k2]
#A = [0.5 0.7;2.1 1.2]
r = [1,1]
K = [2,3]
x0 = [1.7,0.4]
t0 = 0
tf = 50
dt = 0.01

t, sol = pruebas(x0,t0,tf,dt,r,K)

LoadError: UndefVarError: pruebas not defined

In [28]:
p1 = plot(t,sol[:,1],label ="",w=2)
plot!(t,sol[:,2],label ="",w=2)

p2 = plot(sol[:,1],sol[:,2],w=2,
    #xlabel = "Tiempo",
    xlabel = "Conejos",
    ylabel = "Ovejas",
    label = "",
    xlim = [0,4],
    ylim = [0,4]
)
scatter!((sol[1,1],sol[1,2]),label="")
plot(p1,p2,size=(900,400))

LoadError: BoundsError: attempt to access 201×1 Matrix{Float64} at index [1:201, 2]

# 27 de febrero, 2023

Regresamos a ver que pez con el código.

In [29]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

In [30]:
#A = [r1/k1 r1α/k1;r2β/k2 r2/k2]
#A = [0.5 0.7;2.1 1.2]
r = [2,3]
K = [2,3]
x0 = sample(0:0.01:4,2)
t0 = 0
tf = 50
dt = 0.01

(t, sol), A = pruebas(x0,t0,tf,dt,r,K)

LoadError: UndefVarError: sample not defined

In [31]:
p1 = plot(t,sol[:,1],label ="Especie 1",w=2)
plot!(t,sol[:,2],label ="Especie 2",w=2)

p2 = plot(sol[:,1],sol[:,2],w=2,
    #xlabel = "Tiempo",
    xlabel = "Conejos",
    ylabel = "Ovejas",
    label = "",
    xlim = [0,4],
    ylim = [0,4]
)
scatter!((sol[1,1],sol[1,2]),label="t0")
plot(p1,p2,size=(900,400))

LoadError: BoundsError: attempt to access 201×1 Matrix{Float64} at index [1:201, 2]

In [32]:
A

LoadError: UndefVarError: A not defined

¡Lo logré! ya coinciden estas gráficas con el espacio fase que se encuentra en elementos básicos, ahora queda extenderlo a los otros sistemas de más especies, con la intención de que respeten su capacidad de carga.

In [33]:
x0 = rand(5)
t0 = 0
tf = 50
dt = 0.1
r = rand(5)
K = 2*ones(5)

t, sol = cincoEspecies(x0,t0,tf,dt,r,K)

LoadError: UndefVarError: cincoEspecies not defined

In [34]:
plot(t,sol[:,1],label ="Especie 1",w=2)

plot!(t,sol[:,2],label ="Especie 2",w=2)
plot!(t,sol[:,3],label ="Especie 3",w=2)
plot!(t,sol[:,4],label ="Especie 4",w=2)
plot!(t,sol[:,5],label ="Especie 5",w=2)

LoadError: BoundsError: attempt to access 201×1 Matrix{Float64} at index [1:201, 2]

### Ahora ya con la red aleatoria

In [35]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

In [36]:
x0 = sample(0:0.01:3,5)
t0 = 0
tf = 50
dt = 0.1


p = 0.1
N = 5
#r = [2,3]
#K = [2,3]
r = 2*ones(N)
K = 3*ones(N)

params = [N,p,r,K]

(t, sol),A = poblacionesLK(x0,t0,tf,dt,params)

LoadError: UndefVarError: sample not defined

In [37]:
plot(t,sol[:,1],label ="Especie 1",w=2)

plot!(t,sol[:,2],label ="Especie 2",w=2)
plot!(t,sol[:,3],label ="Especie 3",w=2)
plot!(t,sol[:,4],label ="Especie 4",w=2)
plot!(t,sol[:,5],label ="Especie 5",w=2)

LoadError: BoundsError: attempt to access 201×1 Matrix{Float64} at index [1:201, 2]

In [38]:
display(A)

LoadError: UndefVarError: A not defined

## 5 de marzo 2023

En esta ocasión vamos a visualizar el sistema resultante y sacaremos su jacobiano para determinar la estabilidad del sistema.

In [39]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

In [40]:
display(sistemaLK(A,r,K))

LoadError: UndefVarError: sistemaLK not defined

## 16 de marzo, 2023

Definiendo el sistema con base en las entradas aleatorias de la matriz aleatoria.

In [41]:
function sistema(X,A) 
    return  A*X
end
    
    

sistema (generic function with 1 method)

In [42]:
sistema(ones(5),A)

LoadError: UndefVarError: A not defined

In [43]:
A*ones(5)

LoadError: UndefVarError: A not defined

In [44]:
using NLsolve

function f!(F, x)
    F[1] = (x[1]+3)*(x[2]^3-7)+18
    F[2] = sin(x[2]*exp(x[1])-1)
end

function j!(J, x)
    J[1, 1] = x[2]^3-7
    J[1, 2] = 3*x[2]^2*(x[1]+3)
    u = exp(x[1])*cos(x[2]*exp(x[1])-1)
    J[2, 1] = x[2]*u
    J[2, 2] = u
end

nlsolve(f!, j!, [ 0.1; 1.2])

Results of Nonlinear Solver Algorithm
 * Algorithm: Trust-region with dogleg and autoscaling
 * Starting Point: [0.1, 1.2]
 * Zero: [-3.7818049096324184e-16, 1.0000000000000002]
 * Inf-norm of residuals: 0.000000
 * Iterations: 4
 * Convergence: true
   * |x - x'| < 0.0e+00: false
   * |f(x)| < 1.0e-08: true
 * Function Calls (f): 5
 * Jacobian Calls (df/dx): 5

## 23 marzo 2023


In [45]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

In [46]:
x0 = [ 0.65
 1.39
 0.95
 0.42
 3.91]#sample(0:0.01:4,5)
#=A = [1.0        0.0      13.5989   -3.28364  0.0;
 0.0        1.0       0.0       6.10228  0.0;
 0.574493   0.0       1.0       2.74343  0.0;
 2.59557   -3.14685  -2.20031   1.0      0.0;
 0.0        0.0       0.0       0.0      1.0;
]=#
t0 = 0
tf = 50
dt = 0.1

p = 0.5
N = 5
#r = [2,3]
#K = [2,3]


r = 2*ones(N)
K = 3*ones(N)

params = [N,p,r,K]
(t, sol),(_,solE),A,g = poblacionesLK(x0,t0,tf,dt,params)

#(t, sol1),A = pruebas(x0,t0,tf,dt,r,K)

LoadError: UndefVarError: poblacionesLK not defined

In [47]:
p1 = plot(t,sol[:,1],label ="Especie 1",w=2)

plot!(t,sol[:,2],label ="Especie 2",w=2,title="RK4")
plot!(t,sol[:,3],label ="Especie 3",w=2)
plot!(t,sol[:,4],label ="Especie 4",w=2)
plot!(t,sol[:,5],label ="Especie 5",w=2)
#=plot!(t,sol[:,6],label ="Especie 6",w=2)
plot!(t,sol[:,7],label ="Especie 7",w=2)
plot!(t,sol[:,8],label ="Especie 8",w=2)
plot!(t,sol[:,9],label ="Especie 9",w=2)
plot!(t,sol[:,10],label ="Especie 10",w=2)=#

p2 = plot(t,solE[:,1],label ="Especie 1",w=2,title="Euler")

plot!(t,solE[:,2],label ="Especie 2",w=2)
plot!(t,solE[:,3],label ="Especie 3",w=2)
plot!(t,solE[:,4],label ="Especie 4",w=2)
plot!(t,solE[:,5],label ="Especie 5",w=2)

plot(p1,p2,size=(900, 350))

LoadError: BoundsError: attempt to access 201×1 Matrix{Float64} at index [1:201, 2]

In [48]:
display(A)
#gplot(g,nodelabel=1:N)

LoadError: UndefVarError: A not defined

In [49]:
x0

5-element Vector{Float64}:
 0.65
 1.39
 0.95
 0.42
 3.91

### Recordatorio

Habíamos definido en una de nuestras reuniones que la función sistemas no nos muestra como tal la serie de tiempo del sistema, porque nos estamos basando en una matriz aleatoria y en el corazón de la función, no se están poniendo las ecuaciones de LK sino solamente como se visualiza la matriz aleatoria en serie de tiempo. En otras palabras, esta función no corresponde con la serie de tiempo de la dinámica de las 5 especies.

In [50]:
x0 = sample(0:0.01:4,2)
t0 = 0
tf = 50
dt = 0.001

(t, sol) = sistemas(x0,t0,tf,dt,A)

LoadError: UndefVarError: sample not defined

In [51]:
plot(t,sol[:,1],label ="Especie 1",w=2)

plot!(t,sol[:,2],label ="Especie 2",w=2)
#plot!(t,sol[:,3],label ="Especie 3",w=2)
#plot!(t,sol[:,4],label ="Especie 4",w=2)
#plot!(t,sol[:,5],label ="Especie 5",w=2)

LoadError: BoundsError: attempt to access 201×1 Matrix{Float64} at index [1:201, 2]

## 11 de mayo, 2023

Después de casi dos meses batallando con el sistema las conclusiones son que el sistema funciona bien, y es aplicable a cualquier tipo de sistema de $N$ especies. Sin embargo se ocupa de un reescalamiento del sistema en sus números aleatorios, ya que operar con números menores que uno afecta la dinámica de forma que excede la capacidad de carga, poner enteros facilita el problema y para ello damos un factor de escala $\times 10$ para que se ajuste adecuadamente.

En la siguiente entrada voy a investigar area plot y desarrollar más este tema del reescalamiento.


In [52]:
areaplot(t, 
    sol[:,1], 
    seriescolor = [:magenta],
    fillalpha = [0.6],
    label="Especie 1"
)
areaplot!(t, 
    sol[:,2], 
    seriescolor = [:orange],
    fillalpha = [0.5],
    label="Especie 2"
)
areaplot!(t, 
    sol[:,3], 
    seriescolor = [:red],
    fillalpha = [0.4],
    label="Especie 3"
)
areaplot!(t, 
    sol[:,4], 
    seriescolor = [:green],
    fillalpha = [0.4],
    label="Especie 4"
)
areaplot!(t, 
    sol[:,5], 
    seriescolor = [:blue],
    fillalpha = [0.3],
    label="Especie 5"
)

LoadError: BoundsError: attempt to access 201×1 Matrix{Float64} at index [1:201, 2]

In [53]:
areaplot(1:3, [1 2 3; 7 8 9; 4 5 6], seriescolor = [:red :green :blue], fillalpha = [0.2 0.3 0.4])

#### Jacobiano del sistema

Tenemos dos tipos de derivadas parciales para este jacobiano, las de la identidad y las derivadas de la parte triangular superior e inferior.

$$
\frac{\partial f_i(x_i)}{\partial x_i}=r_i\left(1-\frac{\sum_j a_{ij}x_j}{K}\right)-\frac{r_ix_i}{K};\qquad \text{donde }a_{ii}=1
$$

y para el otro caso tenemos

$$
\frac{\partial f_i(x_j)}{\partial x_j}=-\frac{r_ix_i a_{ij}}{K}
$$

In [54]:
N = 5
r = 2*ones(N)
K = 3*ones(N)
A = ones(5,5)
P = [r,K,N,A]
Jacobiano(ones(N),P)

LoadError: UndefVarError: Jacobiano not defined

In [55]:
2*(1-5/3)-2/3

-2.0

Vamos a hallar las raíces del sistema, ya tenemos construido el Jacobiano del mismo ahora solo falta verificar que funciona para el sistema de $2\times 2$. Una vez hecho eso recurrimos a generar un método de newton-rhapson generalizado en donde podamos determinar los puntos críticos del sistema. Para ello seguimos la regla recursiva

$$
v_{i+1}=v_i-(J(v_i))^{-1}f(v_i)
$$



In [56]:
#Ejemplo para el caso de una dimensión
tempCritica(T) = 2*tanh(1/T)^2 - 1 

function Dcentrada(f,a,h)
    derivada = (f(a+h) - f(a-h))/2h
    return derivada
end

function newtonRhapson(f,x_inicial,n)
    h=0.0001
    if n==1
        return x_inicial
    elseif n > 1
        iteracion = newtonRhapson(f,x_inicial,n-1)-f(newtonRhapson(f,x_inicial,n-1))/Dcentrada(f,newtonRhapson(f,x_inicial,n-1),h)
    end
    return iteracion
end

newtonRhapson (generic function with 1 method)

In [57]:
raiz = newtonRhapson(tempCritica,2,10)

1.134592657106511

In [58]:
N = 5
r = 2*ones(N)
K = 3*ones(N)
A = ones(5,5)
P = [r,K,N,A]
nrMulti(Jacobiano,rand(5),P,10)

LoadError: UndefVarError: nrMulti not defined

## 17 mayo

Vamos a poner a prueba el jacobiano y newton rhapson para ver si de verdad encontramos los puntos críticos. Para ello vamos a usar nuestro sistema de prueba de $2\times 2$ para verificar. Para ello hallamos los puntos críticos del siguiente sistema.

$$
A=\begin{pmatrix}
1 & 1\\ 
2 & 1
\end{pmatrix}
$$

El sistema de prueba que usaremos en cuestión es el siguiente.

$$
\begin{cases}
\frac{dx_1}{dt}=2x_1\left(1-\frac{x_1}{2}-\frac{x_2}{2}\right)\\
\frac{dx_2}{dt}=3x_2\left(1-\frac{2x_1}{3}-\frac{x_2}{3}\right)
\end{cases}
$$

Tiene los puntos críticos $x_1=(0,0)$, $x_2=(0,3)$, $x_3=(2,3)$, $x_4=(1,1)$. Verifiquemos.

In [59]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

In [60]:
N = 2
r = [2,3]
K = [2,3]
A = [1 1;2 1]
P = [r,K,N,A]
display(nrMulti(Jacobiano,[1.5,0.9],P,100))
A1 = Jacobiano([1,1],P)
display(A1)
display(eigvals(A1))

LoadError: UndefVarError: nrMulti not defined

In [61]:
N = 5
r = 2*ones(N)
K = 3*ones(N)
A,g = randomMatrix(N,0.1)
P = [r,K,N,A]
x0 = nrMulti(Jacobiano,sample(0:0.1:100,5),P,100)
display(x0)
A1 = Jacobiano(x0,P)
display(A1)
display(eigvals(A1))

LoadError: UndefVarError: randomMatrix not defined

In [62]:
A

2×2 Matrix{Int64}:
 1  1
 2  1

In [63]:
gplot(g,nodelabel=1:5)

LoadError: UndefVarError: gplot not defined

## 18 de mayo, 2023

Vamos a probar todo con sistemas de $2\times 2$ y de $3\times 3$

In [64]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

In [65]:
x0 = sample(0:0.1:4,2)
t0 = 0
tf = 100
dt = 0.1

p = 1
N = 2
#r = [2,3]
#K = [2,3]
r = 2*ones(N)
K = 3*ones(N)

params = [N,p,r,K]
(t, sol),(_,solE),A,g = poblacionesLK(x0,t0,tf,dt,params)

LoadError: UndefVarError: sample not defined

In [66]:
plot(t,sol[:,1],label ="Especie 1")

plot!(t,sol[:,2],label ="Especie 2")

LoadError: BoundsError: attempt to access 201×1 Matrix{Float64} at index [1:201, 2]

In [67]:
A

2×2 Matrix{Int64}:
 1  1
 2  1

### Para $3\times 3$

In [68]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

In [69]:
x0 = sample(0:0.1:4,3)
t0 = 0
tf = 50
dt = 0.1

p = 0.75
N = 3
#r = [2,3]
#K = [2,3]
r = 2*ones(N)
K = 3*ones(N)

params = [N,p,r,K]
(t, sol),(_,solE),A,g = poblacionesLK(x0,t0,tf,dt,params)

LoadError: UndefVarError: sample not defined

In [70]:
plot(t,sol[:,1],label ="Especie 1")

plot(t,sol[:,2],label ="Especie 2")
plot(t,sol[:,3],label= "Especie 3")
axhline(3,c="r",linestyle="--",label=L"K")
legend()

LoadError: BoundsError: attempt to access 201×1 Matrix{Float64} at index [1:201, 2]

In [71]:
xs = collect(0:0.1:10)
ys = collect(0:0.1:10)
zs = collect(0:0.1:10)

X,Y,Z = np.meshgrid(xs,ys,zs)

U = r[1]X - r[1]X.*X/K[1] - r[1]A[1,2]Y.*X/K[1] - r[1]A[1,3]Z.*X/K[3]
V = r[2]Y - r[2]A[2,1]X.*Y/K[2] - r[2]Y.*Y/K[2] - r[2]A[2,3]Z.*Y/K[3]
W = r[3]Z - r[3]A[3,1]X.*Z/K[3] - r[3]A[3,2]Y.*Z/K[3] - r[3]Z.*Z/K[3]
title("Espacio Fase")
#axhline(0,color="gray")
#axvline(0,color="gray")
quiver(X,Y,Z,U,V,W)
xlabel(L"$N_1(t)$")
ylabel(L"$N_2(t)$")
scatter(3,0, label = L"(3,0)")
scatter(0,3, label = L"(0,3)")

legend()

LoadError: UndefVarError: np not defined

## 26 de mayo, 2023

In [72]:
include("../Codigo/main.jl")

LoadError: SystemError: opening file "/home/rogve98/Documentos/Tesis/Tesis/Código/Notebooks/Codigo/main.jl": No existe el archivo o el directorio

### Tarea 3 b)

Tratar de generar un LK estable de 100x100 para  graficar su eigen-valores.

Esta hazaña no es tan sencilla puesto que la probabilidad óptima para que sea susceptible la estabilidad va en función de 

$$
p<\frac{1}{N},\qquad\text{donde $p$ es igual a la probabilidad de interacción}
$$

Transportando eso a 100 especies, nos da espacio para trabajar con probabilidades de $p=0.01$ y aún así hay que ver si funciona.

In [73]:
x0 = sample(0:0.01:4,5)
t0 = 0
tf = 50
dt = 0.1

N = 5
p = 0.5
r = 2*ones(N)
K = 3*ones(N)

params = [N,p,r,K]
(t, sol),_,A,g = poblacionesLK(x0,t0,tf,dt,params)
#(t, sol1),A = pruebas(x0,t0,tf,dt,r,K)

LoadError: UndefVarError: sample not defined

In [74]:
p1 = plot(t,sol[:,1],label ="Especie 1",w=2)

plot!(t,sol[:,2],label ="Especie 2",w=2,title="RK4")
plot!(t,sol[:,3],label ="Especie 3",w=2)
plot!(t,sol[:,4],label ="Especie 4",w=2)
plot!(t,sol[:,5],label ="Especie 5",w=2)
#=plot!(t,sol[:,6],label ="Especie 6",w=2)
plot!(t,sol[:,7],label ="Especie 7",w=2)
plot!(t,sol[:,8],label ="Especie 8",w=2)
plot!(t,sol[:,9],label ="Especie 9",w=2)
plot!(t,sol[:,10],label ="Especie 10",w=2)=#


plot(p1,size=(900, 350))

LoadError: BoundsError: attempt to access 201×1 Matrix{Float64} at index [1:201, 2]

In [75]:
A

2×2 Matrix{Int64}:
 1  1
 2  1

In [76]:
x0

5-element Vector{Float64}:
 0.65
 1.39
 0.95
 0.42
 3.91

In [77]:
P = [r,K,N,A]
raices = nrMulti(Jacobiano,sample(0:0.1:4,5),P,100)
J = Jacobiano(raices,P)
eig = eigvals(J)
print("Raices:")
display(raices)
print("Jacobiano evaluado. Matriz de interacciones")
display(J)
print("Eigenvalores del sistema")
display(eig)

LoadError: UndefVarError: sample not defined

In [78]:
r = sqrt(N*p)
d = -2
scatter(real(eig),imag(eig))
plot!(circulo(d,0,r),seriestype=:shape,
    lw=0.5,
    c = :blue,
    linecolor = :black,
    legend = false,
    fillalpha = 0.2,
    aspect_ratio = 1
)

LoadError: UndefVarError: eig not defined

### Tarea 3 a)

Generar 30 Matrices aleatorias (Jacobianos) de 100x100 y graficar su eigen-valores. Para este caso vamos a aplicar la metodología del May, en donde se salta todos los pasos para llegar al jacobiano y solo considera las matrices aleatorias como matrices de interacción. Sin embargo deben cumplir cierto criterio que dice que la diagonal debe ir con números de la forma $-d$; esto con el objetivo de simular una capacidad de carga en las redes, en donde las especies interactuén consigo mismas negativamente (?).

Para ello es necesario generar una nueva función, ya que randomMatrix no considera ese caso.

In [17]:
include("../../Codigo/main old.jl")

circulo (generic function with 1 method)

In [80]:
N = 100
p = 0.25

J,g = interacciones(N,p,1)

LoadError: UndefVarError: interacciones not defined

In [81]:
display(J)
#display(collect(enlacesAleatorios(N,p)))
gplot(g,nodelabel=1:N)

LoadError: UndefVarError: J not defined

In [82]:
ev = eigvals(J)

LoadError: UndefVarError: J not defined

In [83]:
r = sqrt(N*p)
scatter(real(ev),imag(ev))
plot!(circulo(-1/sqrt(N*p),0,1),seriestype=:shape,
    lw=0.5,
    c = :blue,
    linecolor = :black,
    legend = false,
    fillalpha = 0.2,
    aspect_ratio = 1
)

LoadError: UndefVarError: ev not defined

In [84]:
sqrt(N*p)

5.0

### Vamos a jugar con distribuciones normales

Siendo su definición general

$$
f(x)=\frac{1}{\sigma\sqrt{2\pi}}e^{-\frac{(x-\mu)^2}{2\sigma^2}}
$$

In [2]:
normal(σ,μ,x) = exp(-(x-μ)^2/(2σ^2))/(σ*sqrt(2π))

normal (generic function with 1 method)

In [3]:
xs = range(-10, stop = 10, length = 500)
ys = [normal(1,0,x) for x in xs]

plot(xs ,ys)

In [4]:
r = randn(1000)
histogram(r,bins=100)

In [15]:
d = Normal(0,10)
r = rand(d,1000)
histogram(r,bins=100)

In [16]:
rand(d,10,10)

10×10 Matrix{Float64}:
 12.7035     3.50007   -4.29755   …  -13.619    -12.4107      7.33772
  4.67412   -2.70341    8.86676       13.487    -13.6219     -7.77313
  3.56457    3.92358   15.8341       -10.3197     1.56696     8.69814
 -1.36376   -1.0438     9.36647       -2.43159  -21.4813     -8.31071
  6.47749   -5.50689  -10.7745        29.0348    -3.22469    -6.30533
 -7.98208  -16.1463     0.748154  …   -8.65071   -7.1755     -0.433226
 -5.91215   -3.38857   -9.69854       -1.83009    3.08227    -3.04295
  3.16736   10.4589    -2.71275       -3.74163    7.30322    -2.17541
 -3.52474   -1.68314   -6.77736        9.65109    0.768779   13.1898
 23.1264    -6.96267    7.14164      -21.2732    -1.93273   -11.8588

## 3 de junio, 2023

Vamos a seguir con las tareas precisas de la ley circular tanto con matrices de interacción como con el modelo completo. Primero vamos a verificar lo del artículo de steffano y de ahí vemos como nos movemos con el modelo completo.

Las reglas primordiales de la ley circular que se propone en el artículo es que las matrices en su diagonal son de la forma $M_{ii}=-d$ para representar la capacidad de carga del sistema, es como una muestra de autoregulación; estos términos son importantes ya que si llegan a cambiar, el centro de la ley circular es complejo de definir (como pasa con los jacobianos del sistema completo). Los términos fuera de la diagonal son de la forma

$$
\begin{cases}
M_{ij} = r\qquad\text{con una probabilidad de }p\\
M_{ij} = 0\qquad\text{con la probabilidad }1-p
\end{cases}
$$

donde $r$ es un número aleatorio tomado de una distribución normal con varianza uno y media cero.
Ya de ahí definimos el centro de la ley círcular como $-d$ y el radio como $\sqrt{Np}$. Sin embargo optamos por normalizar las cantidades de forma que  el radio del círculo es unitario y la matriz de interacciones se ve como $\textbf{M}/\sqrt{Np}$

Por tanto vamos a probar todo esto para distintas distribuciones y confirmar la ley circular. Trabajaremos con 100 especies con una conectividad del 50%, es decir, probabilidad de 0.5. Un detalle interesante emerge cuando $p=1/N$.

In [3]:
include("/home/rogve98/Documentos/Tesis/Tesis/Código/Codigo/main old.jl")

WebIO._IJuliaInit()

circulo (generic function with 1 method)

In [4]:
N = 100
p = 0.5

J1,_ = interacciones(N,p,1,0)
J2,_ = interacciones(N,p,2,0)

([0.0 -0.32961199163128513 … 0.0 0.0; 0.3712420260482523 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], SimpleGraph{Int64}(2463, [[2, 3, 5, 6, 8, 11, 12, 13, 14, 15  …  77, 78, 79, 82, 83, 89, 91, 92, 95, 97], [1, 7, 8, 13, 14, 15, 17, 18, 19, 24  …  65, 72, 75, 76, 80, 81, 87, 93, 96, 98], [1, 4, 6, 7, 9, 10, 12, 16, 17, 18  …  83, 85, 86, 87, 89, 92, 94, 95, 96, 98], [3, 5, 6, 7, 9, 12, 15, 16, 17, 18  …  79, 80, 81, 84, 90, 92, 95, 96, 97, 100], [1, 4, 7, 8, 13, 14, 16, 17, 19, 20  …  83, 84, 86, 88, 89, 90, 91, 95, 96, 97], [1, 3, 4, 7, 10, 14, 16, 17, 20, 24  …  80, 84, 89, 91, 92, 93, 94, 95, 98, 99], [2, 3, 4, 5, 6, 10, 12, 16, 17, 18  …  84, 86, 87, 88, 91, 92, 93, 98, 99, 100], [1, 2, 5, 9, 10, 11, 12, 13, 17, 18  …  77, 78, 79, 81, 84, 85, 86, 89, 95, 98], [3, 4, 8, 11, 16, 19, 20, 22, 23, 24  …  87, 88, 89, 90, 91, 92, 94, 95, 96, 99], [3, 6, 7, 8, 14, 15, 17, 24, 27, 29  …  82, 83, 84, 85, 86, 87, 89, 92, 96, 97]  …  [1, 5, 6, 7, 9, 11, 12, 13, 16, 20  …  80, 81,

In [5]:
ev1 = eigvals(J1)
ev2 = eigvals(J2)

100-element Vector{ComplexF64}:
 -2.0684480357225112 + 0.0im
  -1.714995063683346 - 0.11810462564355552im
  -1.714995063683346 + 0.11810462564355552im
  -1.537396625864468 - 0.7792628946896089im
  -1.537396625864468 + 0.7792628946896089im
 -1.4630167550732325 - 0.8017217493018972im
 -1.4630167550732325 + 0.8017217493018972im
 -1.3836676094262352 - 1.1360864076435422im
 -1.3836676094262352 + 1.1360864076435422im
 -1.3325526736399156 - 0.12500692038782507im
 -1.3325526736399156 + 0.12500692038782507im
 -1.2582631303971774 - 0.5008461768933221im
 -1.2582631303971774 + 0.5008461768933221im
                     ⋮
  1.1828907653525293 + 1.6831248518535609im
  1.3280124297970541 - 0.18797823572551142im
  1.3280124297970541 + 0.18797823572551142im
  1.5330213721712602 - 0.7342362974282053im
  1.5330213721712602 + 0.7342362974282053im
  1.5436007307031625 - 0.24107802160139152im
  1.5436007307031625 + 0.24107802160139152im
  1.6833194693745548 - 1.0495255195241737im
  1.6833194693745548 + 1.049

In [6]:
r = sqrt(N*p)
scatter(real(ev1),imag(ev1))
plot!(circulo(0,0,1),seriestype=:shape,
    lw=0.5,
    c = :blue,
    linecolor = :black,
    legend = false,
    fillalpha = 0.2,
    aspect_ratio = 1
)

In [8]:
r = sqrt(N*p)
scatter(real(ev2),imag(ev2),color="red")
plot!(circulo(0,0,2),seriestype=:shape,
    lw=0.5,
    c = :red,
    linecolor = :black,
    legend = false,
    fillalpha = 0.2,
    aspect_ratio = 1
)

## 14 Junio, 2023

In [94]:
dist = Normal(0,2)
rand(dist,10)

LoadError: UndefVarError: Normal not defined

In [95]:
1/sqrt(.25*100)

0.2

# 27 de diciembre 2023

Vamos a comenzar desde el principio. Vamos a cambiar un poco el enfoque de como estabamos llevando a cabo la tesis, el tema principal para que sea candidata a tesis de física es *la transición de fase* en sistemas complejos. Anteriormente nos tomamos la idea de Robert May centrándonos sobre una red aleatoria y dos parámetros que deciden la estabilidad del sistema. 

En esta ocasión me gustaría cambiar el modelo de red (ya que el modelo de red aleatoria no nos sirve para descripciones realistas); nos vamos a centrar en el modelo de red libre de escala, de Albert-Barabasi. Me gustaría abordar el tema con todo y su ley de potencias y demás. Para comenzar vamos a construir el modelo y de ahí nos vamos a ir tendidos a hacer la conexión con un modelo de dinámica no lineal.

Este modelo hasta lo que se, es evolutivo y depende de un proceso estocástico. Por evolutivo me refiero a que es dinámico y tiene cierta dependencia del tiempo (esa sería una buena hipótesis) por tanto este tipo de matriz no tiene asociada una única matriz de adyacencia, en particular para cada instante (discreto) tiene asociada una matriz de adyacencia, por lo tanto tendremos $N$ matrices de adyacencia las cuales se tendrá que analizar su estabilidad y se debe considerar el sistema dinámico sobre cada matriz de adyacencia.

Sin más preliminares, comenzamos por construir la red de Albert-Barabasi